language: scala

# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
#  - oraclejdk7

sudo: false

env:
  global:
    - JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m"
  matrix:
    - SCRIPTED_TEST="scripted project/*1of2"
    - SCRIPTED_TEST="scripted project/*2of2"

script:
  - sbt "$SCRIPTED_TEST"

