name: CI
on:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: 24
        distribution: zulu
    - run: sbt -v "show name"
    - run: sbt -v "show name"
    - run: sbt -v "show name"
    - run: sbt -v "show name"
    - run: sbt -v "show name"

    - run: sbt -v -J-XX:AOTMode=record -J-XX:AOTConfiguration=app.aotconf "show name"
    - run: sbt -v -J-XX:AOTMode=create -J-XX:AOTConfiguration=app.aotconf -J-XX:AOTCache=app.aot "show name"

    - run: sbt -v -J-XX:AOTCache=app.aot "show name"
    - run: sbt -v -J-XX:AOTCache=app.aot "show name"
    - run: sbt -v -J-XX:AOTCache=app.aot "show name"
    - run: sbt -v -J-XX:AOTCache=app.aot "show name"
    - run: sbt -v -J-XX:AOTCache=app.aot "show name"
