name: CI
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms800M -Xmx800M -Xss6M -XX:ReservedCodeCacheSize=128M -server -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      SCALA_212: 2.12.12
      SCALA_213: 2.13.1
      UTIL_TESTS: utilCache/test;utilControl/test;utilInterface/test;utilLogging/test;utilPosition/test;utilRelation/test;utilScripted/test;utilTracking/test
      SBT_LOCAL: false
    steps:
    - name: Checkout sbt/sbt
      uses: actions/checkout@v2
    - name: Checkout sbt/io
      uses: actions/checkout@v2
      with:
        repository: sbt/io
        ref: develop
        path: io
    - name: Checkout sbt/librarymanagement
      uses: actions/checkout@v2
      with:
        repository: sbt/librarymanagement
        ref: develop
        path: librarymanagement
    - name: Checkout sbt/zinc
      uses: actions/checkout@v2
      with:
        repository: sbt/zinc
        ref: develop
        path: zinc
    - name: Setup
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Cache sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - name: Build and test
      run: |
        sbt -v "scripted project/scripted13"
        rm -rf "$HOME/.ivy2/local" || true
        rm -r $(find $HOME/.sbt/boot -name "*-SNAPSHOT") || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
